// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqyi4FdwNu1vRAkObqf3G1j-VT7tS28b4',
    appId: '1:711219707956:web:977fff988132d5c367ca61',
    messagingSenderId: '711219707956',
    projectId: 'movieapp-2fb3b',
    authDomain: 'movieapp-2fb3b.firebaseapp.com',
    storageBucket: 'movieapp-2fb3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6l2HX-9b2cjsmGvaVjgdUgb66QNstCSY',
    appId: '1:711219707956:android:ab03f2a4ba8ba61d67ca61',
    messagingSenderId: '711219707956',
    projectId: 'movieapp-2fb3b',
    storageBucket: 'movieapp-2fb3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNvvgFSgSky6OYNG5WfOjffUgiKKvI00',
    appId: '1:711219707956:ios:e16a2fd4350e6f4a67ca61',
    messagingSenderId: '711219707956',
    projectId: 'movieapp-2fb3b',
    storageBucket: 'movieapp-2fb3b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrNvvgFSgSky6OYNG5WfOjffUgiKKvI00',
    appId: '1:711219707956:ios:e16a2fd4350e6f4a67ca61',
    messagingSenderId: '711219707956',
    projectId: 'movieapp-2fb3b',
    storageBucket: 'movieapp-2fb3b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqyi4FdwNu1vRAkObqf3G1j-VT7tS28b4',
    appId: '1:711219707956:web:810821757636611367ca61',
    messagingSenderId: '711219707956',
    projectId: 'movieapp-2fb3b',
    authDomain: 'movieapp-2fb3b.firebaseapp.com',
    storageBucket: 'movieapp-2fb3b.firebasestorage.app',
  );
}
